### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/ChartCircle' 

### ISSUE THREAD

**Issue by jasonbutt** [chartbrew/strapi-plugin-chartbrew#1]
Installed Chart Brew plugin. Strapi 4.2.2

1. yarn add @chartbrew/plugin-strapi
2. added plugins.js
3. added chartbrew export
4. yarn build

Build failed with ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/ChartCircle'  - Full Error output in the attached errornote.txt
[errornote.txt](https://github.com/chartbrew/strapi-plugin-chartbrew/files/9028759/errornote.txt)

**Comment by razvanilin** [comment]
I just gave it a try with 4.2.2 and it worked. My guess is that there is something going on with the `node_modules`. Let me know if it works after trying the method above :)

**Comment by jasonbutt** [comment]
Thanks. I was able to get it to go by manually installing the module.  ChartBrew plugin now working.  Thanks for the help!
