### ISSUE TITLE
Node18 Support

### ISSUE THREAD

**Issue by matthewdenison** [chartbrew/strapi-plugin-chartbrew#12]
According to the Strapi [quick-start documentation](https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html), Node18 is now supported. The latest Chartbrew plugin supports up to Node16 and causes project errors. Is there any chance the plugin can support Node18 as well?

**Comment by razvanilin** [comment]
Hey @matthewdenison, haven't tried it on 18 but will have a look asap and keep you update 👌

**Comment by razvanilin** [comment]
Just gave it a test and it works on my end with Node 18. Can you share your error logs here + exact Node and Strapi versions?

**Comment by matthewdenison** [comment]
That is good news. I was running Strapi 4.5.1 on Node 18.1.0. When I ran a 'yarn install' it complained about the chartbrew node version. I am not in front of a computer so I don't remember the error verbatim but it was along the lines of 'node version not <= 16.x.x' while fetching and installing the package. I can get the exact error for you a bit later today though.

**Comment by matthewdenison** [comment]
I was able to get the exact error message for you.

Node Version: 18.1.0
Strapi Versions: 4.5.1-4.5.3

```
yarn install v1.22.19  
[1/5] Validating package.json...  
[2/5] Resolving packages...  
[3/5] Fetching packages...  
error @chartbrew/plugin-strapi@0.3.1: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.1.0"  
error Found incompatible module.
```

**Comment by razvanilin** [comment]
The latest version of the plugin is 0.4.1, can you try updating your project's `package.json` to include the latest version of the plugin and try the yarn install command again?

**Comment by matthewdenison** [comment]
Thanks for the update! I just tried it but unfortunately had the same error.

```
error @chartbrew/plugin-strapi@0.4.1: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.1.0"
error Found incompatible module.
```

**Comment by matthewdenison** [comment]
I noticed the package.json file still has
```
"engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
```

**Comment by razvanilin** [comment]
Apologies for the delay on this one, been caught up in a few things. I'll look into it now 👌

**Comment by razvanilin** [comment]
I just increased the node support in the new version 0.4.2. Can you update and let me know if it works?

**Comment by matthewdenison** [comment]
That did it! Thanks for doing that.
