### ISSUE TITLE
error "Something went wrong with the authentication" for chartbrew to connected strapi

### ISSUE THREAD

**Issue by tirajetw** [chartbrew/strapi-plugin-chartbrew#13]
i use my local for chartbrew to connected strapi. But i got alert error "Something went wrong with the authentication. Please check the host and token are correct and try again.". How do i fix this? Thank you
![Screenshot 2565-12-27 at 21 58 31](https://user-images.githubusercontent.com/25123311/209684240-3cf8897b-a603-4c34-b365-f35164b35b49.png)

`strapi version v4.3.2`

**Comment by razvanilin** [comment]
Hey @tirajetw apologies for the delay, I missed the notification for this one.

Is your local copy of Chartbrew working if you go to localhost:4018 and log in?

**Comment by HarjasSodhi** [comment]
Hi @razvanilin. I am also facing this issue while setting up the plugin. I followed all the steps for the self hosted version of chartbrew. Both the frontend and backend on ports 4018 and 4019 are working perfectly. But, I am not able to connect strapi and receiving the same error as in the image. Any help would be much appreciated. Also, i can provide any more info that you might need.

**Comment by razvanilin** [comment]
Hey @HarjasSodhi are you able to access Chartbrew from the machine where your Strapi instance is running from?

Also, can you let me know what version of Strapi are you using?

**Comment by HarjasSodhi** [comment]
Yes. Both strapi and chartbrew were running locally on the same machine. They both were working fine. 
The only problem I encountered was connecting strapi to the chartbrew instance.

I am on strapi v4.9.0

**Comment by Xrythidon** [comment]
I'm heaving the same issue. Both locally running. POST http://localhost:1337/chartbrew/settings returns a 200. But UI shows: Authentication failed

Something went wrong with the authentication. Please check the host and token are correct and try again.

**Comment by razvanilin** [comment]
Updated the readme with instructions on how to solve the issue. Closing this for now

**Comment by juan-wu** [comment]
> Ok, I think I found the issue and this should affect those instances where Strapi is connecting to Chartbrew with an `http://` connection. I was able to replicate the issue and traced it back to Content Security Policy where Strapi is blocking any requests made to an unsecured URL.
> 
> To fix this, you are going to have to modify the `/config/middlewares.js` file and allow connections to `http`. If you already have `strapi::security` in your middleware file, replace the line with the object below:
> 
> ```
> module.exports = [
> ...
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           'connect-src': ["'self'", 'http:', 'https:'],
>           upgradeInsecureRequests: null,
>         },
>       },
>     },
>   },
> ...
> ];
> ```
> 
> Also, don't forget to build your Strapi again after making this change: `npm run build`
> 
> Let me know if this fixes the issue for you all ✌️

Hi razvanilin,

I followed your instruction by adding this code to the strapi/config/middlewares.ts file and then run the command npm run build. After these, I use npm run develop and got the following error

![image](https://github.com/user-attachments/assets/709cb65b-716d-4ee0-834d-46a7bbb9244d)
