### ISSUE TITLE
support for Node 20.x.x

### ISSUE THREAD

**Issue by scot875** [chartbrew/strapi-plugin-chartbrew#15]
Hello, would love to use this plug in with the latest strapi.. I'm currently running:
Strapi version
v4.15.4
node version
v20.10.0

Can this project be updated to run with Node 20.x?

Thanks!

**Comment by razvanilin** [comment]
hey @scot875 👋 sorry this issue went under radar and just noticed it. I added this to the todo list for tomorrow. Will update when a new version is available 👌
