### ISSUE TITLE
Strapi 5

### ISSUE THREAD

**Issue by yevhenskakun** [chartbrew/strapi-plugin-chartbrew#17]
Do you plan to support strapi v5?

**Comment by razvanilin** [comment]
Yup! Aiming to do this quite soon on a v5 branch over here. I looked a bit into it and I don't think I can support both versions with the same code. I'll update here when I have something that works

**Comment by thematrixdev** [comment]
looking forward to having it

**Comment by razvanilin** [comment]
Hoping to have this done next week 🤞 I made a new PR to track the progress -> #19

**Comment by razvanilin** [comment]
Chartbrew for Strapi v5 is now available on `master`. It is released on npm as a major version 2.0.0

https://github.com/chartbrew/strapi-plugin-chartbrew/releases/tag/v2.0.0
