### ISSUE TITLE
Windows Dev - error: 400 - "Missing required arguments to create the template

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/strapi-plugin-chartbrew#2]
This seems to be the error message I am getting: StatusCodeError: 400 - "Missing required arguments to create the template" when trying to create new charts on a new or (using an)existing dashboard.

I also attached another screenshot, that shows the localhost chartbrew dashboard. I tried to run this 3 times, and there are 3 "users reports" listed there. I also had tried to make a category-stats report. So it seems that it partially worked. But when I open those dashboards they appear to be empty.

![Error - 2 -Creating Strapi User Charts](https://user-images.githubusercontent.com/96550228/177198738-2f1cd7e6-b64d-407c-9823-716ffdbae61b.png)

I installed the strapi plugin, into my working strapi backend project. The plugin seems to be up and running as expected, as far as I can tell. I configured all of it, as you explained in your recent youtube video, and based on information I see in the readme file(s).

So once all that was up and running, I tried to create a set of charts for my strapi users, and it is not working. As soon as I clicked the "Create the charts" button, I get the error messages in the console, that you see in the attached text file.  Also, I attached a screenshot of my working strapi chartbrew plugin.

[missing requireed arguments when creating new charts.txt](https://github.com/chartbrew/chartbrew/files/9041243/missing.requireed.arguments.when.creating.new.charts.txt)

![Error Creating Strapi User Charts](https://user-images.githubusercontent.com/96550228/177196868-1200e566-75cb-47ea-a5f4-f71af289aa6e.png)

Here is the error

[2022-07-04 12:02:43.557] http: GET /chartbrew/settings (33 ms) 200
[2022-07-04 12:02:44.257] error: 400 - "Missing required arguments to create the template"
StatusCodeError: 400 - "Missing required arguments to create the template"
    at new StatusCodeError (C:\code\backend\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\code\backend\node_modules\request\request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at Request.<anonymous> (C:\code\backend\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at IncomingMessage.<anonymous> (C:\code\backend\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
From previous event:
    at Request.plumbing.init (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:36:28)
    at Request.RP$initInterceptor [as init] (C:\code\backend\node_modules\request-promise-core\configure\request2.js:41:27)
    at new Request (C:\code\backend\node_modules\request\request.js:127:8)
    at request (C:\code\backend\node_modules\request\index.js:53:10)
    at Object.generate (C:\code\backend\node_modules\@chartbrew\plugin-strapi\server\services\chartbrew.js:111:11)
    at async Object.generateTemplate (C:\code\backend\node_modules\@chartbrew\plugin-strapi\server\controllers\chartbrew.js:64:23)
    at async returnBodyMiddleware (C:\code\backend\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (C:\code\backend\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\body.js:51:9
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (C:\code\backend\node_modules\@koa\cors\index.js:95:16)
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
    at async session (C:\code\backend\node_modules\koa-session\index.js:41:7)
    at async  C:\code\backend\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5

**Comment by razvanilin** [comment]
I transferred this issue to the plugin repository since it seems it's more related to it than to the main Chartbrew repo.

I just read through the info you shared and the charts that don't get generated might be affected by the plugin sending the wrong collection name (possibly).

Can you inspect the chart that is not working in Chartbrew (on Vercel) and see what goes wrong there?

First, click on the chart to enter Edit mode, then select the dataset and click on Request data as shown in the picture:

![CleanShot 2022-07-07 at 10 38 51@2x](https://user-images.githubusercontent.com/5342321/177718869-0252566a-16cf-42f3-a198-ef10ffa2cef7.jpg)

Then check if the API call is configured correctly on the page that appears:

![CleanShot 2022-07-07 at 10 40 36@2x](https://user-images.githubusercontent.com/5342321/177719101-82fa9e2a-e5df-4b2c-9317-3c176f3b1eb7.jpg)

**Comment by scottdevopsgithub** [comment]
OK, I will check into this as soon as possible. I did for a quick minute last night, pop into my (vercel) self-hosted chartbrew instance.  And I saw the chart in there. I clicked the ... on the chart (that was created from the strapi plugin) to see how it was configured. It was defaulted to a KPI option. But that is as far as I got. So I will look a lot more closely and report back

**Comment by scottdevopsgithub** [comment]
Hey, now this is interesting. All I did was go back to the browser tab that has my self-hosted chartbrew frontend up and running...and I hit the refresh button. And now there is data showing up as you can see in the screenshot.  Now, keep in mind, I ended up deleting the other 3 charts last night. I figured since they didnt appear to be working I would just remove them while inside the chartbrew dashboard. But I left this one, just so I could investigate further today.  So just wanted to let you know this happened. I will post more info soon.

![image](https://user-images.githubusercontent.com/96550228/177806003-b8c8541d-d113-4130-b803-3ba553659b77.png)

**Comment by scottdevopsgithub** [comment]
So, maybe this means the charts as (created by the strapi chartbrew plugin) were actually created properly, but for some reason, they didnt have any data in them? I tried this entire process two times yesterday with two different strapi content types and the same thing happened. What it created was empty or blank...when viewing the four charts the chartbrew plugin had created (when viewing in the self-hosted vercel chartbrew dashboard) and when viewing in the strapi chartbrew plugin screen.  Since they were all blank, I had figured they didnt work and I deleted all but this one above. Now I am glad I didnt delete it. Because we can see it does appear to be working today.

I am not sure what that means...as to why they all were blank initially. But just thought I would mention all this.

**Comment by razvanilin** [comment]
Ah right! I think this happens because the chart loaded on Strapi before it was able to make the request to generate the chart from the data. A simple refresh a few seconds after the chart is created should make it display properly in the future

**Comment by scottdevopsgithub** [comment]
Ok, so I tested again with a different strapi content type. 
1. From the Chartbrew plugin Dashboard page, I clicked "Create new visualizations"
2. I chose a strapi content type, and chose to make 2 of the reports this time.
3. Then I clicked 'Create the Charts button'
4. I got the same error as I showed above (the one in the browser that says this in screenshot)

![image](https://user-images.githubusercontent.com/96550228/177902905-3a3ebf85-b71c-4f96-9fcf-3250c14b264b.png)

5. However, this time I just clicked back button in browser which took me back to the Chartbrew Dashboard page in my strapi admin panel. And I saw the two new charts got created, but were empty with no data in them.
6. I logged into the self-hosted chart brew instance, and I saw the charts were there. 
7. I right clicked in them, and chose the Refresh data option. And as soon as I did that, I saw the proper data.
8. Then I went back into my (self-hosted on heroku) strapi admin panel and refreshed the page. And the charts showed up properly.

So at this point, I am not sure why I am getting that error message

**Comment by scottdevopsgithub** [comment]
actually I did just notice something else...if you look in the error message screenshot right above here, the URL seems to be missing the /admin/ part of it. 
So it should be  https://myherokuappname.com/admin/plugins/chartbrew
but instead it looks like it goes to https://myherokuappname.com/plugins/chartbrew

Which gives the error.

**Comment by razvanilin** [comment]
Thanks for the detailed write-up! It's strange that it doesn't get the right URL in your Strapi instance. Are you running your Strapi in `production`, by the way?

**Comment by scottdevopsgithub** [comment]
yes, it should be in production mode when its processed by heroku. I believe I see the production mode mentioned in the heroku logs when its building it

**Comment by scottdevopsgithub** [comment]
Here are a few tidbits from my heroku logs for the strapi backend
-----> Node.js app detected
-----> Creating runtime environment
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

And for the chartbrew backend on heroku
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

**Comment by scottdevopsgithub** [comment]
> Thanks for the detailed write-up! It's strange that it doesn't get the right URL in your Strapi instance. Are you running your Strapi in `production`, by the way?

Is it possible that is a bug?

**Comment by razvanilin** [comment]
I think the main issues described here were solved so I'm going to close this. Feel free to open new issues if anything else is broken as this is now a bit difficult to parse
