### ISSUE TITLE
Issue on height styling on BarChart in Strapi Dashboard 

### ISSUE THREAD

**Issue by Dominic-Preap** [chartbrew/strapi-plugin-chartbrew#3]
## Current behavior

Hi, there is a bit issue on `height` styling of `PolarChart` inside the box like show in the image. If I reduce the size around to `280px` to `270px`, it should look better.

https://github.com/chartbrew/strapi-plugin-chartbrew/blob/6a3091121e5062f1fc62430f9444bfcb939376af/admin/src/components/ChartbrewCharts/PolarChart.js#L49-L53

![image](https://user-images.githubusercontent.com/14802170/180615127-d1b17091-66ce-4673-bdca-dd5a085116e5.png)

## Environment

```
  - Node version: v16.15.0  
  - @strapi/strapi: v4.3.0-beta.1
  - @chartbrew/plugin-strapi: v0.2.7  
  - Platform: Windows 
```

**Comment by razvanilin** [comment]
I don't see a polar chart in the screenshot you posted in this issue. I can definitely see that the bar charts are showing outside of the boxes a bit which is not good. Are all the bar charts showing like that or it only happens when something is added alongside them?

**Comment by Dominic-Preap** [comment]
Sorry it was the bar chart

**Comment by razvanilin** [comment]
Hey @Dominic-Preap could you update the plugin to the latest version and let me know if you still see the issue in your dashboard?

**Comment by Dominic-Preap** [comment]
Just got update to v0.3.0:

- The avg chart type can render but not center in card
- The bar charts still have the same height issue

![image](https://user-images.githubusercontent.com/14802170/181516029-8b2bfbac-e01f-4f4b-a132-5d0351824feb.png)

**Comment by razvanilin** [comment]
I was able to replicate the issue with the avg chart not centering the value. It happens on `medium`, `large`, and `full width` sizes. I'll fix this in the next update.

Regarding the bar charts, I still haven't been able to replicate the issue on my side. I tried multiple screen sizes, chart types and sizes, but no luck. Are you using some other plugins or similar to modify the styles within your Strapi instance?

**Comment by Dominic-Preap** [comment]
I used a few plugins, here is my dependencies I used:

```
  "dependencies": {
    "@chartbrew/plugin-strapi": "0.3.0",
    "@strapi/plugin-i18n": "4.3.0",
    "@strapi/plugin-users-permissions": "4.3.0",
    "@strapi/strapi": "4.3.0",
    "moment": "2.29.4",
    "mysql": "2.18.1",
    "strapi-plugin-config-sync": "1.0.2",
    "strapi-plugin-generate-data": "1.0.11",
    "strapi-plugin-meilisearch": "0.7.1",
    "strapi-plugin-react-editorjs": "2.0.1"
  },
```

**Comment by razvanilin** [comment]
v1.0.0 comes with a new layout for the dashboard and it fixes the styling issues too. Closing this
