### ISSUE TITLE
Bug: average chart does not render properly in Strapi dashboard

### ISSUE THREAD

**Issue by Dominic-Preap** [chartbrew/strapi-plugin-chartbrew#5]
## Current behavior

Average chart type does not render in Strapi Admin.

![image](https://user-images.githubusercontent.com/14802170/180616277-786bb745-9440-46ec-9cfe-6e508e3aa015.png)

![image](https://user-images.githubusercontent.com/14802170/180616316-4727d5bd-24ca-4095-86e6-c84abe63f4b7.png)

## Environment

```
  - Node version: v16.15.0  
  - @strapi/strapi: v4.3.0-beta.1
  - @chartbrew/plugin-strapi: v0.2.7  
  - Platform: Windows 
```

**Comment by razvanilin** [comment]
The average type is missing indeed. I will add in the new release which should be out next week :)

**Comment by razvanilin** [comment]
Support for avg chart type was just added in 77a288c7bebfdfbc340e4a048d4b6dcde635777a
