### ISSUE TITLE
Add moment to package.json

### ISSUE THREAD

**Issue by ramit-mitra** [chartbrew/strapi-plugin-chartbrew#6]
I tried to install the plugin and `run run build` on a fresh Strapi v4 project and got an error - missing `moment`. Manually installing moment using `npm i moment` and then running `build` and `start` worked fine. Hence I think it should be better to add moment to `package.json`. 

Package:
- https://www.npmjs.com/package/moment

**Comment by razvanilin** [comment]
Good find @ramit-mitra 👍 I think I already had moment installed in my Strapi instances and didn't notice this. I'll update asap

**Comment by scottdevopsgithub** [comment]
I just noticed this today also. Once I added moment to my backend strapi admin panel project, it was happy after that.

**Comment by scottdevopsgithub** [comment]
yarn run v1.22.19
$ cross-env FORCE_COLOR=1 npm-run-all -l -p develop:*
$ yarn --cwd backend develop
$ wait-on http://localhost:1337/admin && yarn --cwd frontend develop
$ strapi develop
[develop:backend ] Building your admin UI with development configuration...
[develop:backend ] i Compiling Webpack
[develop:backend ] ModuleNotFoundError: Module not found: Error: Can't resolve 'moment' in 'C:\code\chartbrew\backend\node_modules\@chartbrew\plugin-strapi\admin\src\utils'

**Comment by razvanilin** [comment]
I just checked the release notes for Strapi and it looks like they removed `moment` entirely in 4.3.0, hence the error in the plugin. I will publish a minor release now to fix this issue

**Comment by ramit-mitra** [comment]
Thankyou 👍
