### ISSUE TITLE
[BUG] Create the charts button does not work - Strapi backend URL is not populated

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/strapi-plugin-chartbrew#7]
At the end of this thread there is some more specific error logic I have noticed. Not sure why this is all happening though. Still, there is good screenshots and comments in here too. Thank you for your help!

I will be debugging it more tonight...

Have you ever seen this happen? I got the chartbrew plugin loaded up, configured etc (it is running in the heroku cloud, with a postgres database). I deployed the latest Corporate starter pack Admin panel (and that is where I installed the Chartbrew plugin too).  I have seen this happen on localhost version of the Admin Panel, as well as in the heroku version. That is the version you see in the screenshot.

Thought I did everything correctly...but when I try to create a new Data Visualization from my strapi collections in the Heroku version of the strapi Admin Panel, there are no options to choose from. It says "Select the charts you want to create"...but there are none listed.

![image](https://user-images.githubusercontent.com/96550228/187767817-72897af6-d39e-4b90-a47f-b3e0ae2d438e.png)

**Comment by scottdevopsgithub** [comment]
I have got this working before in a different (and similiar implementation) and used that to compare any differences. I am not sure why it doesnt seem to be working here in this strapi Admin Panel. Was hoping you might have an idea about what I may have done wrong? Or maybe that you have seen this happen before.

**Comment by scottdevopsgithub** [comment]
I logged in with the Owner account, and created a new API from there (I had been logged in and using a Test user account which was not the owner). Once I did that, now I can at least see the list of charts showing up, when I click on the different strapi collection types. But no matter if I choose an existing dashboard to place the charts, or leave that field blank and let it create a new dashboard....it doesnt do anything,

I mean, when I click the Create the Charts button, the screen flashes briefly, and no charts are created in the Chartbrew frontend. As in the screenshot below it did create a 'pages repot' dashboard, but no charts are actually created in there.

When I look at the actual running Chartbrew frontend, I see the 'pages report' but it is empty.

Any idea why, when clicking the Create the charts, it ends up not creating anything???

![image](https://user-images.githubusercontent.com/96550228/187772585-fec25bf9-9e5f-4df4-b138-2197b4d9855b.png)

**Comment by scottdevopsgithub** [comment]
Here is the Dashboard screen, after it did create the 'pages report', but notice its empty. Nothing was created :-(

![image](https://user-images.githubusercontent.com/96550228/187773067-23edf55b-23ba-46b6-b87f-3df852cda66c.png)

**Comment by scottdevopsgithub** [comment]
Here is what the Chartbrew admin panel looks like after attempting to create those data visualizations of the Strapi data. Notice the 'pages repot' is there. But when I open it up...its totally empty

![image](https://user-images.githubusercontent.com/96550228/187773450-eb19d2ca-978f-4591-8f84-28d5dd40143d.png)

**Comment by scottdevopsgithub** [comment]
Also, here is another project I created in the Chartbrew Admin panel like shown in the screenshot above.
And when I refresh the strapi chartbrew plugin, you can see it there. So there is some communications happening here between the entities involved.

![image](https://user-images.githubusercontent.com/96550228/187775077-198849ca-8bd8-4022-b3cf-e2b7e00cb981.png)

**Comment by scottdevopsgithub** [comment]
And here is when I just now had created it in the Chartbrew Admin screen. 
![image](https://user-images.githubusercontent.com/96550228/187775317-3f021e1a-8831-424e-bd81-450c0f794629.png)

**Comment by scottdevopsgithub** [comment]
And here is my Chartbrew plugin settings. 
![image](https://user-images.githubusercontent.com/96550228/187776135-1e92e447-f0f7-4139-b930-4d8165462f5b.png)

**Comment by scottdevopsgithub** [comment]
I checked the heroku logs, for where this strapi Admin Panel is running, and notice the error I am getting when I try to click the Create the Charts button. Hopefully this will be helpful to determine what is going wrong??

![image](https://user-images.githubusercontent.com/96550228/187780285-bd8a2f10-48fe-4ad1-87c8-7728a99aacc5.png)

**Comment by scottdevopsgithub** [comment]
Here is the chartbrew code where I see this error message may be coming from

![image](https://user-images.githubusercontent.com/96550228/187791380-14baf01a-6854-4c8f-b1fd-f2d0d2006d7f.png)

**Comment by scottdevopsgithub** [comment]
![image](https://user-images.githubusercontent.com/96550228/187792258-67070985-567d-48c1-92ba-81a6d8395d9d.png)

**Comment by scottdevopsgithub** [comment]
Also, for what its worth, when I attempt to run this on localhost where I initially got the strapi admin panel running (and then added the chartbrew plugin, and configured it)....that is broken too. Seeing two potential errors

![image](https://user-images.githubusercontent.com/96550228/187798507-a328459f-74b9-4868-bbdb-c5c35b1f10cd.png)

**Comment by razvanilin** [comment]
Thanks for the detailed logs and all the debugging @scottdevopsgithub 🙏 I'll look into it and let you know as soon as I find the issue

**Comment by scottdevopsgithub** [comment]
Im still digging into whatever I can. Hope you find something soon. :-)

**Comment by scottdevopsgithub** [comment]
PS I  am wondering, in the interim, if I could rollback to 1.22.1 of Chartbrew (I just realized that line of code I showed above was in the chartbrew repo and not the Chartbrew plugin repo)

Well anyways, I believe I had it working in that 1.22.1 version. What do you think? 
Here is what I am running right now in the Strapi Admin Panel that is hosting my Chartbrew plugin

![image](https://user-images.githubusercontent.com/96550228/187810834-d8d0809a-c6a4-46b8-8d64-b3fb427515f8.png)

**Comment by razvanilin** [comment]
I tried Strapi 4.2.2 and 4.3.6 and I could not replicate the issues (using the latest plugin and chartbrew versions).

Some other things I tried:
- Create a dashboard with an `Editor` role in Strapi
- Create a dashboard with an `Author` role
- Refresh both Chartbrew token and the Strapi one

Can you let me know what roles the `Mr Dashboard` Chartbrew user has?

Also, can you try and refresh the tokens to see if that fixes the issue?

**Comment by scottdevopsgithub** [comment]
OK, let me try these things. Ill let you know what I find. may have a question for you about these things.

**Comment by scottdevopsgithub** [comment]
![image](https://user-images.githubusercontent.com/96550228/187829290-42f8bc04-b9e0-469c-9eda-f2b668d27f62.png)

**Comment by scottdevopsgithub** [comment]
![image](https://user-images.githubusercontent.com/96550228/187829367-cd13ca5d-f3a7-46da-b8c3-c52a436f66de.png)

**Comment by scottdevopsgithub** [comment]
I did create a new token while logged in to Chartbrew admin panel as Mr Dashboard (owner). And I put that token into the Chartbrew plugin.  Here is what I see when I click the test button using the newest token I created when in the chartbrew admin panel earlier today
![image](https://user-images.githubusercontent.com/96550228/187829645-7cf6e8ea-ed49-405e-9f51-6bf270989b0f.png)

**Comment by scottdevopsgithub** [comment]
PS, is there any possibility I have something wrong in my ENV vars that could cause something like this? I just wanted to mention it. I thought I entered them all properly, but who knows.

**Comment by scottdevopsgithub** [comment]
I created an Editor Account, logged in as that user, and attempted to create a new Visualization. Got same error in the terminal window.
But also, as before, it does at least create an empty 'project' in the Chartbrew Admin panel

![image](https://user-images.githubusercontent.com/96550228/187831478-361c7305-3bc0-4dfb-8ba5-bd4524d7678c.png)

**Comment by scottdevopsgithub** [comment]
So, just for the heck of it, I went into the Chartbrew Dashboard and created a new Connection, and pointed to one of my strapi blog sites with a public facing API. I saved the dataset etc. Then I made a new chart from it, while in Chartbrew Admin panel. 

Then I went back to the Chartbrew Plugin/dashboard screen in my Strapi Admin Panel, and I can see the chart I just created. So it is working OK from that standpoint.

![image](https://user-images.githubusercontent.com/96550228/187833004-33dc9fb5-179f-46f6-843d-a5a1abc41931.png)

**Comment by scottdevopsgithub** [comment]
By the way what is this for? Am I supposed to fill this in?  I noticed this was empty.

![image](https://user-images.githubusercontent.com/96550228/187834586-dd8a5a71-4318-4db2-acb6-d4409c29adc0.png)

**Comment by razvanilin** [comment]
> ![image](https://user-images.githubusercontent.com/96550228/187792258-67070985-567d-48c1-92ba-81a6d8395d9d.png)

Would it be possible for you to add the following lines in the chartbrew code at line 322?

```
console.log("templateData", templateData);
```

Maybe easier to do it on the localhost version of Chartbrew. Something is missing from the data and this will give me a better idea in what to investigate

**Comment by scottdevopsgithub** [comment]
I may need to clarify something here. The version of Chartbrew that I am using, came into existence by me forking the chartbrew repo, and then just pointing a heroku app at that github repo. So my current Chartbrew is hosted in heroku and not on local machine.

I think the chartbrew code you are referring to, would be located inside of that instance of my heroku version, isnt that correct?

So, is there anyway to make this happen whilst still using my forked copy of the chartbrew code (located in my heroku app)?

**Comment by scottdevopsgithub** [comment]
Here you go
![image](https://user-images.githubusercontent.com/96550228/187939629-bceee749-bfac-432b-950d-e24d019dcc5e.png)

**Comment by scottdevopsgithub** [comment]
These are the config vars, masked, for this running instance (forked copy) of chartbrew

![image](https://user-images.githubusercontent.com/96550228/187940185-4c16c0b9-c25d-4edd-af3e-422ed9455e27.png)

**Comment by scottdevopsgithub** [comment]
PS Am I supposed to fill this in? I am not sure what the purpose of this is...

![image](https://user-images.githubusercontent.com/96550228/187941144-b6eeafcf-2f18-4771-8b98-0670155535f2.png)

**Comment by scottdevopsgithub** [comment]
Just to put the results here at end, easier to spot from the screenshots above.

_It seems to be telling me that strapiHost is empty?? Not sure why that would be. Can you tell me where that is set at? is it taking it from an ENV var?_

**Comment by razvanilin** [comment]
Hmm, it looks like the Admin UI can't find the backend URL from the env variables.

The line in question is here: https://github.com/chartbrew/strapi-plugin-chartbrew/blob/master/admin/src/pages/Create/index.js#L28

Maybe for now, you can set this manually where you deployed Strapi. The Env variable that needs to be set is `STRAPI_ADMIN_BACKEND_URL`

The value depends on your backend URL. For example on localhost this would be `http://localhost:1337` by default

**Comment by scottdevopsgithub** [comment]
Hello, thanks for info. Im parsing it now...

**Comment by scottdevopsgithub** [comment]
PS you said
_1. It looks like the Admin UI can't find the backend URL from the env variables_
Are you talking about the Chartbrew frontend/Admin UI or my Strapi Admin UI?

**Comment by razvanilin** [comment]
> PS you said _1. It looks like the Admin UI can't find the backend URL from the env variables_ Are you talking about the Chartbrew frontend/Admin UI or my Strapi Admin UI?

Strapi's Admin UI. So you will need to set up the variable in the place where you've deployed Strapi. That variable should be set automatically, so not really sure why it's not working

**Comment by scottdevopsgithub** [comment]
alrighty, so these are my ENV vars in the heroku instance that is hosting the Strapi Admin panel. Looks like there is no sign of a STRAPI_ADMIN_BACKEND_URL

![image](https://user-images.githubusercontent.com/96550228/188053908-e5b341f7-0681-4cc3-a0b9-0dd2b0ed2db3.png)

**Comment by razvanilin** [comment]
You will need to add it there for now. Normally that gets populated automatically by Strapi so there's no need to set it up there. But it seems it doesn't work on your end for some reason. I'll need to see how I can handle this differently in the plugin

**Comment by scottdevopsgithub** [comment]
OK, I will add it and deploy and hopefully that resolves this!

**Comment by scottdevopsgithub** [comment]
its working better this time! But, there's always a but lol....I think we discussed this other issue before. But at least part of it makes more sense to me this time around. Let me post a few more screenshots....and let me know if I should create a new issue.

**Comment by scottdevopsgithub** [comment]
![image](https://user-images.githubusercontent.com/96550228/188055400-25ae8428-00da-45a8-a507-3019428622cc.png)

**Comment by scottdevopsgithub** [comment]
It created the charts, but the data doesnt show up, until I went into the Chartbrew Admin panel, and hit the refresh button. Then it showed up as seen below

**Comment by scottdevopsgithub** [comment]
![image](https://user-images.githubusercontent.com/96550228/188055522-27b46e07-df43-4837-90c8-46b9003e4225.png)

**Comment by scottdevopsgithub** [comment]
And lastly, I see what is happening here, but I dont know why. After it creates the charts it redirects back to https://backend.herokuapp.com/plugins/chartbrew

It does that each time I made some new charts. So its repeatable consistently each time.

But instead it should be redirecting to here instead:
https://backend.herokuapp.com/admin/plugins/chartbrew

So its like missing the /admin/ part of the URL during the redirect

So anyways, to solve it for now, I just manually put in https://chartbrewcorpbackend-staging.herokuapp.com/admin/plugins/chartbrew and hit enter, and then it shows the screenshot you see above.

![image](https://user-images.githubusercontent.com/96550228/188055657-90449364-b56c-4abc-bb91-af57e61c3dce.png)

**Comment by scottdevopsgithub** [comment]
thanks for your help!

**Comment by razvanilin** [comment]
Thanks a lot for all the details and debugging! I'll have a look into these issues as soon as I can.

For now, I separated these into separate issues because the discussion here is getting very difficult to parse

**Comment by scottdevopsgithub** [comment]
Yep, I see the other new issues. If I can troubleshoot anymore I will add more info :-)

**Comment by scottdevopsgithub** [comment]
Just wondering, do you have any hunches or guesstimates, of where I might start looking in the chartbrew code to do more debugging on those other two issues? If not, thats fine too... I will just start 'somewhere in the middle' :-)

**Comment by scottdevopsgithub** [comment]
> You will need to add it there for now. Normally that gets populated automatically by Strapi so there's no need to set it up there. But it seems it doesn't work on your end for some reason. I'll need to see how I can handle this differently in the plugin

Do you think maybe we need another text box in the Chartbrew plugin Settings in the Strapi Admin panel, where we could type in the URL for the STRAPI_ADMIN_BACKEND_URL. And if the strapi backend url is null/undefined at runtime, then you use the value of the STRAPI_ADMIN_BACKEND_URL that is specified in a new Chartbrew settings value?

**Comment by scottdevopsgithub** [comment]
PS, been debugging some more...not sure what this is about, Connection refused? hmmm
I think it happens four times (once for each chart it is trying to get data for? or push data back into the strapi instance?)


022-09-02T05:11:02.414934+00:00 app[web.1]: Unhandled rejection RequestError: Error: connect ECONNREFUSED 0.0.0.0:80
2022-09-02T05:11:02.414937+00:00 app[web.1]:     at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)
2022-09-02T05:11:02.414938+00:00 app[web.1]:     at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
2022-09-02T05:11:02.414939+00:00 app[web.1]:     at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
2022-09-02T05:11:02.414939+00:00 app[web.1]:     at self.callback (/app/node_modules/request/request.js:185:22)
2022-09-02T05:11:02.414939+00:00 app[web.1]:     at Request.emit (node:events:513:28)
2022-09-02T05:11:02.414940+00:00 app[web.1]:     at Request.onRequestError (/app/node_modules/request/request.js:877:8)
2022-09-02T05:11:02.414940+00:00 app[web.1]:     at ClientRequest.emit (node:events:513:28)
2022-09-02T05:11:02.414941+00:00 app[web.1]:     at Socket.socketErrorListener (node:_http_client:481:9)
2022-09-02T05:11:02.414941+00:00 app[web.1]:     at Socket.emit (node:events:513:28)
2022-09-02T05:11:02.414941+00:00 app[web.1]:     at emitErrorNT (node:internal/streams/destroy:157:8)
2022-09-02T05:11:02.414942+00:00 app[web.1]:     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
2022-09-02T05:11:02.414942+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-09-02T05:11:02.415073+00:00 app[web.1]: Unhandled rejection RequestError: Error: connect ECONNREFUSED 0.0.0.0:80
2022-09-02T05:11:02.415074+00:00 app[web.1]:     at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)
2022-09-02T05:11:02.415075+00:00 app[web.1]:     at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
2022-09-02T05:11:02.415075+00:00 app[web.1]:     at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
2022-09-02T05:11:02.415075+00:00 app[web.1]:     at self.callback (/app/node_modules/request/request.js:185:22)
2022-09-02T05:11:02.415076+00:00 app[web.1]:     at Request.emit (node:events:513:28)
2022-09-02T05:11:02.415076+00:00 app[web.1]:     at Request.onRequestError (/app/node_modules/request/request.js:877:8)
2022-09-02T05:11:02.415076+00:00 app[web.1]:     at ClientRequest.emit (node:events:513:28)
2022-09-02T05:11:02.415076+00:00 app[web.1]:     at Socket.socketErrorListener (node:_http_client:481:9)
2022-09-02T05:11:02.415077+00:00 app[web.1]:     at Socket.emit (node:events:513:28)
2022-09-02T05:11:02.415077+00:00 app[web.1]:     at emitErrorNT (node:internal/streams/destroy:157:8)
2022-09-02T05:11:02.415078+00:00 app[web.1]:     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
2022-09-02T05:11:02.415078+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-09-

**Comment by scottdevopsgithub** [comment]
also, wondering if strapi permissions issues are playing into this or not. I have to spend a little time to inspect those...

**Comment by razvanilin** [comment]
I'll close this because I created separate issues #9 and #8
