### ISSUE TITLE
[BUG] Wrong URL redirection after the charts are created

### ISSUE THREAD

**Issue by razvanilin** [chartbrew/strapi-plugin-chartbrew#9]
And lastly, I see what is happening here, but I dont know why. After it creates the charts it redirects back to https://backend.herokuapp.com/plugins/chartbrew
and shows the error you see below in the screenshot.

It does that each time I made some new charts. So its repeatable consistently each time.

But instead it should be redirecting to here instead:
https://backend.herokuapp.com/admin/plugins/chartbrew

So its like missing the /admin/ part of the URL during the redirect

So anyways, to solve it for now, I just manually put in https://backend.herokuapp.com/admin/plugins/chartbrew and hit enter, and then it shows the screenshot you see above.

![image](https://user-images.githubusercontent.com/96550228/188055657-90449364-b56c-4abc-bb91-af57e61c3dce.png)

_Originally posted by @scottdevopsgithub in https://github.com/chartbrew/strapi-plugin-chartbrew/issues/7#issuecomment-1235039934_

**Comment by scottdevopsgithub** [comment]
I would have to find the place in the chartbrew code where the /admin/ is being read/assigned....and I am thinking that value is not used during the redirect. Instead the value of /admin/ is not added into the redirect...and therefore you see the problem in the screenshot above. 

so maybe need to add the /admin/ in some cases?

**Comment by razvanilin** [comment]
I'm aware of the issue now, no worries. I'll fix it as soon as I have some free time

**Comment by scottdevopsgithub** [comment]
awesome! thanks!
